.PHONY: clean All

All:
	@echo "----------Building project:[ challenge - Debug ]----------"
	@cd "challenge" && "$(MAKE)" -f  "challenge.mk"
clean:
	@echo "----------Cleaning project:[ challenge - Debug ]----------"
	@cd "challenge" && "$(MAKE)" -f  "challenge.mk" clean
